# Generated by Django 5.2.5 on 2025-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="website",
        ),
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
